// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helloworld.proto

package helloworld

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	WidgetID             int64             `protobuf:"varint,1,opt,name=widgetID,proto3" json:"widgetID,omitempty"`
	WidgetName           string            `protobuf:"bytes,2,opt,name=widgetName,proto3" json:"widgetName,omitempty"`
	ShopID               int64             `protobuf:"varint,3,opt,name=shopID,proto3" json:"shopID,omitempty"`
	Data                 []*DynamicRequest `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetWidgetID() int64 {
	if m != nil {
		return m.WidgetID
	}
	return 0
}

func (m *Request) GetWidgetName() string {
	if m != nil {
		return m.WidgetName
	}
	return ""
}

func (m *Request) GetShopID() int64 {
	if m != nil {
		return m.ShopID
	}
	return 0
}

func (m *Request) GetData() []*DynamicRequest {
	if m != nil {
		return m.Data
	}
	return nil
}

type DynamicRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DynamicRequest) Reset()         { *m = DynamicRequest{} }
func (m *DynamicRequest) String() string { return proto.CompactTextString(m) }
func (*DynamicRequest) ProtoMessage()    {}
func (*DynamicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{1}
}

func (m *DynamicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DynamicRequest.Unmarshal(m, b)
}
func (m *DynamicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DynamicRequest.Marshal(b, m, deterministic)
}
func (m *DynamicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DynamicRequest.Merge(m, src)
}
func (m *DynamicRequest) XXX_Size() int {
	return xxx_messageInfo_DynamicRequest.Size(m)
}
func (m *DynamicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DynamicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DynamicRequest proto.InternalMessageInfo

func (m *DynamicRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DynamicRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *DynamicRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Response struct {
	ErrorMessage         string   `protobuf:"bytes,1,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	ErrorCode            string   `protobuf:"bytes,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Body                 []byte   `protobuf:"bytes,3,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *Response) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

func (m *Response) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "helloworld.Request")
	proto.RegisterType((*DynamicRequest)(nil), "helloworld.DynamicRequest")
	proto.RegisterType((*Response)(nil), "helloworld.Response")
}

func init() { proto.RegisterFile("helloworld.proto", fileDescriptor_17b8c58d586b62f2) }

var fileDescriptor_17b8c58d586b62f2 = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x41, 0x4f, 0x83, 0x40,
	0x10, 0x85, 0x45, 0x6a, 0x85, 0xb1, 0x9a, 0x66, 0x6c, 0x0c, 0x21, 0xc6, 0x10, 0x4e, 0x9c, 0x38,
	0xd4, 0xab, 0x27, 0xcb, 0xc1, 0x26, 0x6a, 0xcc, 0x7a, 0xf0, 0xea, 0x2a, 0x93, 0xd2, 0x48, 0x59,
	0x64, 0xb7, 0x36, 0xfc, 0x08, 0xff, 0xb3, 0x61, 0xa0, 0x16, 0x6e, 0xef, 0x7d, 0x61, 0xe6, 0xbd,
	0x61, 0x61, 0x9a, 0x51, 0x9e, 0xab, 0x9d, 0xaa, 0xf2, 0x34, 0x2e, 0x2b, 0x65, 0x14, 0xc2, 0x81,
	0x84, 0xbf, 0x16, 0x9c, 0x0a, 0xfa, 0xde, 0x92, 0x36, 0xe8, 0x83, 0xb3, 0x5b, 0xa7, 0x2b, 0x32,
	0xcb, 0xc4, 0xb3, 0x02, 0x2b, 0xb2, 0xc5, 0xbf, 0xc7, 0x1b, 0x80, 0x56, 0x3f, 0xcb, 0x0d, 0x79,
	0xc7, 0x81, 0x15, 0xb9, 0xa2, 0x47, 0xf0, 0x0a, 0xc6, 0x3a, 0x53, 0xe5, 0x32, 0xf1, 0x6c, 0x9e,
	0xec, 0x1c, 0xc6, 0x30, 0x4a, 0xa5, 0x91, 0xde, 0x28, 0xb0, 0xa3, 0xb3, 0xb9, 0x1f, 0xf7, 0xca,
	0x24, 0x75, 0x21, 0x37, 0xeb, 0xcf, 0x2e, 0x5d, 0xf0, 0x77, 0xe1, 0x23, 0x5c, 0x0c, 0x39, 0x4e,
	0xc1, 0xfe, 0xa2, 0x9a, 0x0b, 0xb9, 0xa2, 0x91, 0x88, 0x30, 0x32, 0x75, 0xb9, 0x6f, 0xc1, 0x1a,
	0x67, 0x70, 0xf2, 0x23, 0xf3, 0x2d, 0x71, 0xbc, 0x2b, 0x5a, 0x13, 0xbe, 0x83, 0x23, 0x48, 0x97,
	0xaa, 0xd0, 0x84, 0x21, 0x4c, 0xa8, 0xaa, 0x54, 0xf5, 0x44, 0x5a, 0xcb, 0x15, 0x75, 0x0b, 0x07,
	0x0c, 0xaf, 0xc1, 0x65, 0xbf, 0x50, 0xe9, 0x7e, 0xfd, 0x01, 0x34, 0xb9, 0xf7, 0x2a, 0xad, 0x39,
	0x62, 0x22, 0x58, 0xcf, 0x1f, 0xc0, 0x79, 0xcd, 0x54, 0xf9, 0xd2, 0x4c, 0xdf, 0xc1, 0xf9, 0x1b,
	0xff, 0x91, 0x45, 0x26, 0x8b, 0x82, 0x72, 0xbc, 0xec, 0x9f, 0xdb, 0xdd, 0xe3, 0xcf, 0x86, 0xb0,
	0x6d, 0x17, 0x1e, 0x7d, 0x8c, 0xf9, 0x71, 0x6e, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd8, 0x8b,
	0xe7, 0x22, 0xb0, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ShopPageClient is the client API for ShopPage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShopPageClient interface {
	WidgetChannel(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type shopPageClient struct {
	cc *grpc.ClientConn
}

func NewShopPageClient(cc *grpc.ClientConn) ShopPageClient {
	return &shopPageClient{cc}
}

func (c *shopPageClient) WidgetChannel(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/helloworld.ShopPage/WidgetChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShopPageServer is the server API for ShopPage service.
type ShopPageServer interface {
	WidgetChannel(context.Context, *Request) (*Response, error)
}

// UnimplementedShopPageServer can be embedded to have forward compatible implementations.
type UnimplementedShopPageServer struct {
}

func (*UnimplementedShopPageServer) WidgetChannel(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WidgetChannel not implemented")
}

func RegisterShopPageServer(s *grpc.Server, srv ShopPageServer) {
	s.RegisterService(&_ShopPage_serviceDesc, srv)
}

func _ShopPage_WidgetChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopPageServer).WidgetChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.ShopPage/WidgetChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopPageServer).WidgetChannel(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShopPage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.ShopPage",
	HandlerType: (*ShopPageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WidgetChannel",
			Handler:    _ShopPage_WidgetChannel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld.proto",
}
